export const STATE = {
  NO_REPO: 'NO_REPO',
  REBASING: 'REBASING',
  MERGING: 'MERGING',
  CHERRY_PICKING: 'CHERRY_PICKING',
  REVERTING: 'REVERTING',
  BISECTING: 'BISECTING',
  APPLYING_MAILBOX: 'APPLYING_MAILBOX',
  OK: 'OK',
}
