os: osx
osx_image: xcode9.4
language: node_js
node_js:
  - "8.11.3"
cache: 
  yarn: true
  directories:
    - "node_modules"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "1.7.0"
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: "Test"
      name: "Linting"
      os: linux
      script: yarn lint
    - name: "Unit Tests"
      os: linux
      script: yarn test
    - stage: "Build"
      script: yarn pack:mac
      deploy:
        provider: releases
        api_key: $GITHUB_API_KEY
        file_glob: true
        file: "dist/Giterm-*.dmg"
        skip_cleanup: true
        draft: true
        on:
          branch: travis-build