trigger:
- master
- azure-pipelines

pool:
  vmImage: 'ubuntu-16.04'

stages:
- stage: JSChecks
  jobs:
  - job: JSChecks
    steps:
    - script: |
        nvm use
        yarn install
      displayName: Install
    - script: |
        yarn lint
      displayName: Lint
    - script: |
        yarn ci:test
      displayName: Unit Tests

- stage: Build
  jobs:
  - job: Mac
    pool:
      vmImage: 'macOS-10.15'
    steps:
    - script: |
        nvm use
        yarn install
      displayName: Install
    - script: |
        yarn pack:mac
        rm -rf dist/mac
      displayName: Build
    - publish: $(Build.SourcesDirectory)/dist 
      artifact: GitermMac

  - job: Linux
    steps:
    - script: |
        nvm use
        yarn install
      displayName: Install
    - script: |
        yarn pack:linux
        rm -rf dist/linux-unpacked
      displayName: Build
    - publish: $(Build.SourcesDirectory)/dist 
      artifact: GitermLinux
      
  - job: Windows
    pool:
      vmImage: 'windows-2019'
    steps:
    - script: |
        nvm use
        yarn install
      displayName: Install
    - script: |
        yarn pack:win
        rmdir dist\win-unpacked /s /q
      displayName: Build
    - publish: $(Build.SourcesDirectory)/dist 
      artifact: GitermWindows
