trigger:
  branches:  
    include:
    - master
  tags:
    include:
    - v*.*.*

variables:
- group: GITERM_CERT_GROUP

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: JSChecks
  jobs:
  - job: JSChecks
    steps:
    - task: UseNode@1
      inputs:
        version: '10.x'
        checkLatest: true
    - script: |
        sudo apt install libkrb5-dev
        yarn install --network-timeout=100000
        yarn build-js
      displayName: Install
    - script: |
        yarn lint
      displayName: Lint
    - script: |
        yarn test
      displayName: Unit Tests

- stage: Build
  jobs:
  - job: Mac
    pool:
      vmImage: 'macOS-10.15'
    steps:
    - task: UseNode@1
      inputs:
        version: '10.x'
        checkLatest: true
    - task: DownloadSecureFile@1
      displayName: Download Application Signing Certificate
      name: certApp
      inputs:
        secureFile: 'DevIdApplication.p12'
    - script: |
        yarn install --network-timeout=100000
      displayName: Install
    - script: |
        yarn build-js
      displayName: Build Packages
    - script: |
        cd packages/giterm
        yarn pack:mac
        yarn rimraf dist/mac
      displayName: Build
      env:
        APPLEID: $(GITERM_APPLEID_UN)
        APPLEIDPASS: $(GITERM_APPLEID_PW)
        CSC_LINK: $(certApp.secureFilePath)
        CSC_KEY_PASSWORD: $(GITERM_CERT_PW)
    - publish: $(Build.SourcesDirectory)/packages/giterm/dist 
      artifact: GitermMac

  - job: Linux
    steps:
    - task: UseNode@1
      inputs:
        version: '10.x'
        checkLatest: true
    - script: |
        sudo apt install libkrb5-dev
        yarn install --network-timeout=100000
      displayName: Install
    - script: |
        yarn build-js
      displayName: Build Packages
    - script: |
        cd packages/giterm
        yarn pack:linux
        yarn rimraf dist/linux-unpacked dist/.icon-set
      displayName: Build
    - publish: $(Build.SourcesDirectory)/packages/giterm/dist 
      artifact: GitermLinux
      
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: UseNode@1
      inputs:
        version: '10.x'
        checkLatest: true
    - script: |
        yarn install --network-timeout=100000
      displayName: Install
    - script: |
        yarn build-js
      displayName: Build Packages
    - script: |
        cd packages/giterm
        yarn pack:win
      displayName: Build
    - script: |
        yarn rimraf dist/win-unpacked
      displayName: Clean Artifacts
    - publish: $(Build.SourcesDirectory)/packages/giterm/dist 
      artifact: GitermWindows
