trigger:
- master
- azure-pipelines

pool:
  vmImage: 'ubuntu-16.04'

stages:
- stage: JSChecks
  jobs:
  - job: JSChecks
    steps:
    - script: |
        yarn install
      displayName: Install
    - script: |
        yarn lint
      displayName: Lint
    - script: |
        yarn test
      displayName: Unit Tests

- stage: Build
  jobs:
  - job: Mac
    pool:
      vmImage: 'macOS-10.15'
    steps:
    - script: |
        yarn install
      displayName: Install
    - script: |
        yarn pack:mac
      displayName: Build
    - publish: dist/Giterm-*.dmg
      artifact: GitermMac
  - job: Linux
    steps:
    - script: |
        yarn install
      displayName: Install
    - script: |
        yarn pack:linux
      displayName: Build
    - publish: dist/Giterm-*.dmg
      artifact: GitermLinux
  - job: Windows
    pool:
      vmImage: 'windows-2019'
    steps:
    - script: |
        yarn install
      displayName: Install
    - script: |
        yarn pack:win
      displayName: Build
    - publish: dist/Giterm-*.dmg
      artifact: GitermWindows
