trigger:
- master
- azure-pipelines

pool:
  vmImage: 'ubuntu-16.04'

stages:
- stage: JSChecks
  jobs:
  - job: JSChecks
    steps:
    - script: |
        yarn install
      displayName: Install
    - script: |
        yarn lint
      displayName: Lint
    - script: |
        yarn ci:test
      displayName: Unit Tests

- stage: Build
  jobs:
  - job: Mac
    pool:
      vmImage: 'macOS-10.15'
    steps:
    - script: |
        yarn install
      displayName: Install
    - script: |
        yarn pack:mac
        ls
        ls dist
      displayName: Build
    - publish: $(Build.SourcesDirectory)/dist #/Giterm-*.dmg
      artifact: GitermMac

  - job: Linux
    steps:
    - script: |
        yarn install
      displayName: Install
    - script: |
        yarn pack:linux
        ls
        ls dist
      displayName: Build
    - publish: $(Build.SourcesDirectory)/dist #/Giterm-*.deb .AppImage
      artifact: GitermLinux
      
  - job: Windows
    pool:
      vmImage: 'windows-2019'
    steps:
    - script: |
        yarn install
      displayName: Install
    - script: |
        yarn pack:win
        dir
        dir dist
      displayName: Build
    - publish: $(Build.SourcesDirectory)/dist #/Giterm Setup 0.3.0.exe
      artifact: GitermWindows
