export { reducer as branches } from './branches/reducer'
export { reducer as commits } from './commits/reducer'
export { reducer as config } from './config/reducer'
export { reducer as graph } from './graph/reducer'
export { routerReducer as routing } from 'react-router-redux'
export { reducer as status } from './status/reducer'
export { reducer as terminal } from './terminal/reducer'
