export { watch as branches } from './branches/sagas'
export { watch as tags } from './tags/sagas'
export { watch as remotes } from './remotes/sagas'
export { watch as commits } from './commits/sagas'
export { watch as config } from './config/sagas'
export { watch as graph } from './graph/sagas'
export { watch as status } from './status/sagas'
export { watch as emitters } from './emitters/sagas'
