# This is a basic workflow to help you get started with Actions

name: Github Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, github-pages-dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install
      run: yarn install --frozen-lockfile

    # Runs a set of commands using the runners shell
    - name: Build Gatsby
      working-directory: packages/site
      run: yarn build
    
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2.1.2
      with:
        target_branch: gh-pages
        build_dir: packages/site/public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        

    
        
